# Generated by Django 3.2.13 on 2024-01-01 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20240101_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='owener',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='store',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
