# Generated by Django 3.2.13 on 2024-01-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20240102_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='display_picture',
            field=models.ImageField(blank=True, null=True, upload_to='display_pictures/'),
        ),
    ]
