# Generated by Django 3.2.13 on 2024-01-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_store_display_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='address',
            new_name='business_address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='name',
        ),
    ]
