# Generated by Django 4.0.6 on 2022-07-13 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payed_at', models.DateTimeField(auto_now_add=True)),
                ('payment_referance_number', models.CharField(max_length=200)),
                ('status', models.PositiveIntegerField()),
                ('delivery_address', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('state', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
