# Generated by Django 3.2.8 on 2021-10-24 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('channel', models.CharField(max_length=10)),
                ('card_type', models.CharField(max_length=10)),
                ('bank', models.CharField(max_length=30)),
                ('card_last_four', models.CharField(max_length=4)),
                ('county_code', models.CharField(max_length=3)),
                ('account_name', models.CharField(max_length=100)),
                ('refrence_code', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'SUCCESS'), (0, 'FAILED')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
