# Generated by Django 3.2.8 on 2021-10-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='account_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_last_four',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='channel',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='county_code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
