# Generated by Django 3.2.8 on 2021-11-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.IntegerField(choices=[(1, 'SUCCESS'), (0, 'FAILED')], default=0),
        ),
    ]
