# Generated by Django 4.0.6 on 2022-07-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AddField(
            model_name='payment',
            name='delivery_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default='3456', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='state',
            field=models.CharField(default='kno', max_length=20),
            preserve_default=False,
        ),
    ]
