# Generated by Django 3.2.13 on 2023-12-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20231230_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='bio',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='rc_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='store_verification_files/'),
        ),
    ]
