# Generated by Django 3.2.13 on 2024-01-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20240110_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
