# Generated by Django 4.0.6 on 2022-10-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_date_added_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
