# Generated by Django 4.0.6 on 2022-10-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
