# Generated by Django 4.0.6 on 2022-08-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_payment_user_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='country',
            field=models.CharField(default='nigeria', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='first_name',
            field=models.CharField(default='ismail', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='last_name',
            field=models.CharField(default='muhammad', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='postal_code',
            field=models.CharField(default='09789', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'failed'), (1, 'Pending'), (2, 'Success')], default=1),
        ),
    ]
