# Generated by Django 4.0.6 on 2022-08-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_payment_delivery_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
