# Generated by Django 4.0.6 on 2022-10-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_color_product_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='added_by',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product-images'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
