# Generated by Django 3.2.7 on 2021-10-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='supplier',
        ),
        migrations.AddField(
            model_name='cart',
            name='Size',
            field=models.CharField(default='34', max_length=20),
            preserve_default=False,
        ),
    ]
