# Generated by Django 3.2.7 on 2021-10-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Size',
            new_name='size',
        ),
    ]
