# Generated by Django 3.2.7 on 2021-10-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='ismail', max_length=100),
            preserve_default=False,
        ),
    ]
