# Generated by Django 3.2.13 on 2023-12-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20231229_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.DeleteModel(
            name='StoreVerification',
        ),
        migrations.DeleteModel(
            name='VerificationDocument',
        ),
    ]
