# Generated by Django 3.2.8 on 2021-11-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('discount', models.FloatField(default=0.0)),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('delivery_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('PND', 'Pending'), ('PRC', 'Processing'), ('CMP', 'Completed')], default='PND', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
    ]
