# Generated by Django 4.0.6 on 2022-07-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tailor_reciever',
        ),
    ]
