# Generated by Django 3.2.8 on 2021-10-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_products', to='order.order'),
            preserve_default=False,
        ),
    ]
