# Generated by Django 4.0.6 on 2022-08-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Canceled'), (2, 'Recieved'), (3, 'Processing'), (4, 'Pending')], default=4),
        ),
    ]
