# Generated by Django 3.2.8 on 2021-10-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211024_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PND', 'Pending'), ('PRC', 'Processing'), ('CMP', 'Completed')], default='PND', max_length=3),
        ),
    ]
