# Generated by Django 4.0.6 on 2022-07-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_delivery_address_order_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Canceled'), (2, 'Completed'), (3, 'Pending')], default=3),
        ),
    ]
