# Generated by Django 4.0.6 on 2022-07-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_product_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quentity',
        ),
    ]
