# Generated by Django 4.0.6 on 2022-07-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_order_delivery_address_remove_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(default='ewretgrfv', max_length=200),
            preserve_default=False,
        ),
    ]
