# Generated by Django 3.2.7 on 2021-10-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
