# Generated by Django 3.2.8 on 2021-10-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211025_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('U', 'Unisex'), ('M', 'Male'), ('F', 'Female')], default='U', max_length=1),
        ),
    ]
