# Generated by Django 3.2.7 on 2021-10-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211019_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='2', max_length=20),
            preserve_default=False,
        ),
    ]
