# Generated by Django 3.2.7 on 2021-10-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='30, 40, 42, 44', max_length=300),
            preserve_default=False,
        ),
    ]
