# Generated by Django 3.2.8 on 2021-10-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_sizes_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('U', 'Unisex'), ('M', 'Male'), ('F', 'Female')], default='U', max_length=1),
        ),
    ]
