# Generated by Django 4.0.6 on 2022-07-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_available_quantity_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_days',
            field=models.PositiveIntegerField(),
        ),
    ]
