# Generated by Django 3.2.8 on 2021-10-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_days',
            field=models.PositiveIntegerField(),
        ),
    ]
