# Generated by Django 3.2.8 on 2021-10-24 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_delivery_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery_days',
        ),
    ]
