# Generated by Django 3.2.8 on 2021-10-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_delivery_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_days',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
