# Generated by Django 3.2.13 on 2022-10-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20221019_1331'),
        ('products', '0014_alter_category_name'),
    ]

    operations = [
    ]
