# Generated by Django 3.2.13 on 2022-10-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_merge_20221029_0037'),
        ('products', '0016_cart_device'),
    ]

    operations = [
    ]
