# Generated by Django 3.2.13 on 2024-01-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_productvariant_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
    ]
